FROM python:3.13
workdir /app2

COPY . .

RUN apt-get update
RUN apt-get upgrade
#RUN apt-get install vlc -y
#RUN pip install -r requirements.txt

# RUN python3 databaseGenerator.py -m new -d /sound

#CMD ["python3","webbyBits.py"]
RUN ls